Repository sparcs-kaist/new-ara-api, pull requests merged in 2023-08, with the labels that each got.

#403 Fix tests
  ara/settings/dev/__init__.py
  ara/settings/prod/__init__.py
  tests/test_articles.py
  tests/test_communication_article.py
  tests/test_home.py
Labels: bug

#404 Fix tests to use appropriate environment variables
  ara/settings/dev/__init__.py
  ara/settings/prod/__init__.py
  tests/test_articles.py
  tests/test_communication_article.py
  tests/test_home.py
Labels: deploy

#408 Show debug toolbar always
  ara/settings/dev/__init__.py
  ara/settings/django.py
  ara/settings/test.py
  ara/urls.py
Labels: bug

#409 Fix article board group N+1 query problem
  apps/core/views/viewsets/article.py
Labels: bug

#410 Deploy v3.0.1
  apps/core/views/viewsets/article.py
  ara/settings/dev/__init__.py
  ara/settings/django.py
  ara/settings/test.py
  ara/urls.py
Labels: deploy

#407 Add minor features for top articles
  .pre-commit-config.yaml
  apps/core/serializers/article.py
  apps/core/views/viewsets/article.py
Labels: feature
