Repository sparcs-kaist/new-ara-api, pull requests merged in 2024-03, with the labels that each got.

#454 Fix migration conflict
  apps/core/migrations/0044_portalviewcount.py
  apps/core/migrations/0045_article_add_latest_portal_view_count.py
  apps/core/migrations/0046_alter_portal_crawl_related_field.py
  apps/core/migrations/0058_article_latest_portal_view_count_alter_article_url_and_more.py
  apps/core/migrations/0058_merge_20240109_2331.py
  apps/core/models/article.py
  apps/core/models/portal_view_count.py
Labels: bug

#448 [EKS] Fix api url
  apps/core/management/scripts/reminder_email_for_reply.py
  apps/core/views/viewsets/report.py
  ara/settings/prod/__init__.py
Labels: enhancement

#455 Deploy to EKS
  .gitignore
  deployment/.gitignore
  deployment/README.md
  deployment/base/celery/deployment.yaml
  deployment/base/kustomization.yaml
  deployment/base/redis/deployment.yaml
  deployment/base/redis/service.yaml
  deployment/base/server/configmap.yaml
  deployment/base/server/deployment.yaml
  deployment/base/server/ingress.yaml
  deployment/base/server/sealed-secret.yaml
  deployment/base/server/secret-template.yaml
  deployment/base/server/service.yaml
  deployment/overlays/dev/kustomization.yaml
Labels: enhancement

#456 Fix notification displaying nickname on anonymous post
  apps/core/models/notification.py
Labels: bug

#458 Fix Secret keys
  .gitignore
  deployment/base/server/seal.py
  deployment/base/server/sealed-secret.yaml
Labels: deploy

#459 Add celery environ
  deployment/base/celery/deployment.yaml
Labels: deploy
